### ISSUE TITLE
Aero breaks spirit healer on 1.12.1 client

### ISSUE THREAD

**Issue by skeewirt** [gashole/Aero#1]
After trial and error with all mods, this Aero is the only single mod that is causing this bug.

After dying, I speak to the spirit healer, and the normal dialogue box pops up. When I click the resurrect button from dialogue, the following informational box with text about gear being damaged does not pop up. Additionally, the spirit healer does the resurrect animation immediately after hitting the resurrect button on the initial dialogue box.

**Comment by Minnona** [comment]
Can confirm it.

**Comment by shikulja** [comment]
The same

**Comment by gashole** [comment]
Fixed by https://github.com/gashole/Aero/commit/6727d3286722143b1a658eafcf2112e8b0ff0cba

**Comment by shikulja** [comment]
@gashole  no, not fixed

**Comment by gashole** [comment]
Ah, I had to test with a higher level character to see the issue. At low levels, the popup stays visible when the frame reappears, so no problem. After a certain level, it hides. Skipping the hide animation when a popup appears fixes it. I'm going with that.

Fixed by 90301f7
