### ISSUE TITLE
Aero triggers Show/Hide handlers

### ISSUE THREAD

**Issue by SabineWren** [gashole/Aero#2]
Aero animations call Show/Hide extra times, resulting in addons firing their handlers more than once. For example, when opening and closing a dialog:
```
OnShow (expected - Open dialog)
OnHide (expected - Close dialog)
OnShow (not expected - animation starts)
OnHide (not expected - animation ends)
```

In my case, it resulted in 3 sound effects playing at once when closing a dialog. I implemented a [workaround](https://github.com/SabineWren/Quiver/commit/588c9f3a9b41746af2c2e612d536c49bbe40676d), but addon authors who don't use Aero will never encounter that. For example, [AdvancedTradeSkillWindow](https://github.com/laytya/AdvancedTradeSkillWindow-vanilla) demonstrates the same audio bug without a workaround.

Perhaps you could disable or remove events for the duration of the animation.

**Comment by gashole** [comment]
Thanks for the report, fixed by cc487cc
